### ISSUE TITLE
Backend Storage of User Hatchery Input Data

### ISSUE THREAD

**Issue by jadenwest** [dtalton3/wundereats#23]
## Acceptance Criteria
Data to be added under hatchery schema:
- hatchery dimensions 
- number of starting grubs
- feed type
- feed weight
- substrate type
- substrate weight

## Testing
- Integration testing to ensure hatchery input data saves into database

**Comment by xNickyB** [comment]
Made a createHatchery page accessible by (localhost:3000/createHatchery) or by clicking on “My Hatcheries” link in the vertical navbar. Currently creates a UUID and hatcheryName for each hatchery. Regarding UUIDs, I ran into some issues using the UUID-Mongodb npm package, so I followed another GitHub and ended up grabbing the relevant pieces placing them in a new lib folder in the backend (so no “npm install uuid-mongodb” needed). I also found that “_id” acts as the primary key to a document. MongoDB will provide one if we don’t explicitly set an “_id” field. The hatcheries collection is currently using a UUID for the “_id” field, code looks like this from the routes.js file [ _id: MUUID.v4()]. The idea was that Users would receive a UUID at the time of creation. Then, since you can’t create a hatchery unless you are logged in, we could somehow link the users with their hatcheries by user UUID. That way once we figure out how to make user info persist we can do something like     localStorage.getItem('currentUser’).get(“_id”) then find the hatcheries from that. This is kind of still a theory though as I haven’t really tested the idea. Also, I thought one of the issues could be coming from having the backend embedded in the Grubtrak folder so I moved it outside. It’s currently still outside and I don’t want to put it back in and mess up any explicit paths, I can fix it later but just keep it in mind before we decide to merge. Some next steps will be to add UUID as the primary key when users are created and seeing if we can get that info to persist across different pages and finally use to find relevant info about the user, like their hatcheries.

`_id: "192a61ae-41da-4792-8081-f5c54259def7"
hatcheryName: "Jaden's Hatchery"`

<img width="1440" alt="Screen Shot 2021-09-22 at 9 13 20 PM" src="https://user-images.githubusercontent.com/43282483/134441823-78fb060a-d2c4-401f-b219-1d3e5023e464.png">
<img width="893" alt="Screen Shot 2021-09-22 at 9 13 10 PM" src="https://user-images.githubusercontent.com/43282483/134441824-ed6723b9-c621-467e-a57f-e0dc014a4aac.png">
.
