### ISSUE TITLE
Backend Input of Emissions Calculations

### ISSUE THREAD

**Issue by jadenwest** [dtalton3/wundereats#54]
Adding methods to app to code in the math needed to calculate the CO2 equivalent for insects, and compare that to beef, lamb, pork, and chicken CO2 equivalents

**Comment by xNickyB** [comment]
Integrated methods from HatcheryCalculations.js into Modal.js. I ended up having to change the import from
Import HatcheryCalculations =  from "./HatcheryCalculations.js"; to 
const HatcheryCalculations = require("./HatcheryCalculations.js");
Also changed const grubMass = HatcheryCalculations.getGrubMass(numLarvae); to let grubMass = HatcheryCalculations.getGrubMass(numLarvae); it was failing on runtime cause we were assigning to a const. Also got some weird error because of the export basically saying there were no functions in the HatcheryCalculations object so I ended up exporting the functions at the bottom with module.exports = { getTrueHatcheryVolumeValue, getGrubMass, getHatcheryDensity,  getEmissionsCalculationsFromGrubMass}; We still need to incorporate the rest of the attributes like grubmass and density but they’re there working.
